/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java_Main */

#ifndef _Included_Java_Main
#define _Included_Java_Main
#ifdef __cplusplus
extern "C" {
#endif
#undef Java_Main_E_SH_LANG_VERTEX
#define Java_Main_E_SH_LANG_VERTEX 0L
#undef Java_Main_E_SH_LANG_TESS_CONTROL
#define Java_Main_E_SH_LANG_TESS_CONTROL 1L
#undef Java_Main_E_SH_LANG_TESS_EVALUATION
#define Java_Main_E_SH_LANG_TESS_EVALUATION 2L
#undef Java_Main_E_SH_LANG_GEOMETRY
#define Java_Main_E_SH_LANG_GEOMETRY 3L
#undef Java_Main_E_SH_LANG_FRAGMENT
#define Java_Main_E_SH_LANG_FRAGMENT 4L
#undef Java_Main_E_SH_LANG_COMPUTE
#define Java_Main_E_SH_LANG_COMPUTE 5L
#undef Java_Main_E_SH_LANG_RAY_GEN
#define Java_Main_E_SH_LANG_RAY_GEN 6L
#undef Java_Main_E_SH_LANG_INTERSECT
#define Java_Main_E_SH_LANG_INTERSECT 7L
#undef Java_Main_E_SH_LANG_ANY_HIT
#define Java_Main_E_SH_LANG_ANY_HIT 8L
#undef Java_Main_E_SH_LANG_CLOSEST_HIT
#define Java_Main_E_SH_LANG_CLOSEST_HIT 9L
#undef Java_Main_E_SH_LANG_MISS
#define Java_Main_E_SH_LANG_MISS 10L
#undef Java_Main_E_SH_LANG_CALLABLE
#define Java_Main_E_SH_LANG_CALLABLE 11L
#undef Java_Main_E_SH_LANG_TASK_NV
#define Java_Main_E_SH_LANG_TASK_NV 12L
#undef Java_Main_E_SH_LANG_MESH_NV
#define Java_Main_E_SH_LANG_MESH_NV 13L
#undef Java_Main_E_SH_EX_VERTEX_FRAGMENT
#define Java_Main_E_SH_EX_VERTEX_FRAGMENT 0L
#undef Java_Main_E_SH_EX_FRAGMENT
#define Java_Main_E_SH_EX_FRAGMENT 1L
#undef Java_Main_E_SH_OPT_NO_GENERATION
#define Java_Main_E_SH_OPT_NO_GENERATION 0L
#undef Java_Main_E_SH_OPT_NONE
#define Java_Main_E_SH_OPT_NONE 1L
#undef Java_Main_E_SH_OPT_SIMPLE
#define Java_Main_E_SH_OPT_SIMPLE 2L
#undef Java_Main_E_SH_OPT_FULL
#define Java_Main_E_SH_OPT_FULL 3L
#undef Java_Main_E_SH_MSG_DEFAULT
#define Java_Main_E_SH_MSG_DEFAULT 0L
#undef Java_Main_E_SH_MSG_RELAXED_ERRORS
#define Java_Main_E_SH_MSG_RELAXED_ERRORS 1L
#undef Java_Main_E_SH_MSG_SUPRESS_WARNINGS
#define Java_Main_E_SH_MSG_SUPRESS_WARNINGS 2L
#undef Java_Main_E_SH_MSG_AST
#define Java_Main_E_SH_MSG_AST 4L
#undef Java_Main_E_SH_MSG_SPV_RULES
#define Java_Main_E_SH_MSG_SPV_RULES 8L
#undef Java_Main_E_SH_MSG_VULKAN_RULES
#define Java_Main_E_SH_MSG_VULKAN_RULES 16L
#undef Java_Main_E_SH_MSG_ONLY_PREPROCESSOR
#define Java_Main_E_SH_MSG_ONLY_PREPROCESSOR 32L
#undef Java_Main_E_SH_MSG_READ_HLSL
#define Java_Main_E_SH_MSG_READ_HLSL 64L
#undef Java_Main_E_SH_MSG_CASCADING_ERRORS
#define Java_Main_E_SH_MSG_CASCADING_ERRORS 128L
#undef Java_Main_E_SH_MSG_KEEP_UNCALLED
#define Java_Main_E_SH_MSG_KEEP_UNCALLED 256L
#undef Java_Main_E_SH_MSG_HLSL_OFFSETS
#define Java_Main_E_SH_MSG_HLSL_OFFSETS 512L
#undef Java_Main_E_SH_MSG_DEBUG_INFO
#define Java_Main_E_SH_MSG_DEBUG_INFO 1024L
#undef Java_Main_E_SH_MSG_HLSL_ENABLE_16BIT_TYPES
#define Java_Main_E_SH_MSG_HLSL_ENABLE_16BIT_TYPES 2048L
#undef Java_Main_E_SH_MSG_HLSL_LEGALIZATION
#define Java_Main_E_SH_MSG_HLSL_LEGALIZATION 4096L
#undef Java_Main_E_SH_MSG_HLSL_DX9_COMPATIBLE
#define Java_Main_E_SH_MSG_HLSL_DX9_COMPATIBLE 8192L
#undef Java_Main_E_SH_MSG_BUITLIN_SYMBOL_TABLE
#define Java_Main_E_SH_MSG_BUITLIN_SYMBOL_TABLE 16384L
/*
 * Class:     Java_Main
 * Method:    ShInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShInitialize
  (JNIEnv *, jclass);

/*
 * Class:     Java_Main
 * Method:    ShFinalize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShFinalize
  (JNIEnv *, jclass);

/*
 * Class:     Java_Main
 * Method:    ShBinding
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_ShBinding
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     Java_Main
 * Method:    ShBindingTable
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_ShBindingTable
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    ShConstructCompiler
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_ShConstructCompiler
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Java_Main
 * Method:    ShConstructLinker
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_ShConstructLinker
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Java_Main
 * Method:    ShConstructUniformMap
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_ShConstructUniformMap
  (JNIEnv *, jclass);

/*
 * Class:     Java_Main
 * Method:    ShDestruct
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Java_Main_ShDestruct
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    TBuiltInResource
 * Signature: ([I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_TBuiltInResource
  (JNIEnv *, jclass, jintArray, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    TLimits
 * Signature: ([Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_TLimits
  (JNIEnv *, jclass, jbooleanArray);

/*
 * Class:     Java_Main
 * Method:    ShCompile
 * Signature: ([B[Ljava/lang/String;II[BIIZI)I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShCompile
  (JNIEnv *, jclass, jbyteArray, jobjectArray, jint, jint, jbyteArray, jint, jint, jboolean, jint);

/*
 * Class:     Java_Main
 * Method:    ShLinkExt
 * Signature: ([B[BI)I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShLinkExt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     Java_Main
 * Method:    ShSetEncryptionMethod
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Java_Main_ShSetEncryptionMethod
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    ShGetInfoLog
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Java_Main_ShGetInfoLog
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    ShGetExecutable
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_ShGetExecutable
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    ShSetVirtualAttributeBindings
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShSetVirtualAttributeBindings
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    ShSetFixedAttributeBindings
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShSetFixedAttributeBindings
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     Java_Main
 * Method:    ShExcludeAttributes
 * Signature: ([B[II)I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShExcludeAttributes
  (JNIEnv *, jclass, jbyteArray, jintArray, jint);

/*
 * Class:     Java_Main
 * Method:    ShGetUniformLocation
 * Signature: ([BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Java_Main_ShGetUniformLocation
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     Java_Main
 * Method:    allocString
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_allocString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Java_Main
 * Method:    createArray
 * Signature: ([[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Java_Main_createArray
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     Java_Main
 * Method:    free
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Java_Main_free
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
